INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("hello", "hi", 200, "2020-05-11", "2020-08-21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("hello", "hi", 200, "2020-05-11", "2020-08-21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("hello", "hi", 200, "2020-05-11", "2020-08-21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("hello", "hi", 200, "2020-05-11", "2020-08-21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("hello", "hi", 200, "2020-05-11", "2020-08-21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("hello", "hi", 200, "2020-05-11", "2020-08-21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("hello", "hi", 200, "2020-05-11", "2020-08-21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("hello", "hi", 200, "2020-05-11", "2020-08-21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("hello", "hi", 200, "2020-05-11", "2020-08-21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("hello", "hi", 200, "2020-05-11", "2020-08-21");

INSERT INTO users (name, age) VALUES ("bob", 20);
INSERT INTO users (name, age) VALUES ("bob", 20);
INSERT INTO users (name, age) VALUES ("bob", 20);
INSERT INTO users (name, age) VALUES ("bob", 20);
INSERT INTO users (name, age) VALUES ("bob", 20);
INSERT INTO users (name, age) VALUES ("bob", 20);
INSERT INTO users (name, age) VALUES ("bob", 20);
INSERT INTO users (name, age) VALUES ("bob", 20);
INSERT INTO users (name, age) VALUES ("bob", 20);
INSERT INTO users (name, age) VALUES ("bob", 20);
INSERT INTO users (name, age) VALUES ("bob", 20);
INSERT INTO users (name, age) VALUES ("bob", 20);
INSERT INTO users (name, age) VALUES ("bob", 20);
INSERT INTO users (name, age) VALUES ("bob", 20);
INSERT INTO users (name, age) VALUES ("bob", 20);
INSERT INTO users (name, age) VALUES ("bob", 20);
INSERT INTO users (name, age) VALUES ("bob", 20);
INSERT INTO users (name, age) VALUES ("bob", 20);
INSERT INTO users (name, age) VALUES ("bob", 20);
INSERT INTO users (name, age) VALUES ("bob", 20);


INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
